// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSsystem.Api.Models;

#nullable disable

namespace POSsystem.Api.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260206085907_AddChangeToPayment")]
    partial class AddChangeToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSsystem.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A2B81E304FF");

                    b.HasIndex(new[] { "ShopId", "Name" }, "UQ_Category_Shop_Name")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId")
                        .HasName("PK__Country__10D160BFF0F7C5C3");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ExpenseCategoryID");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.HasKey("ExpenseId")
                        .HasName("PK__Expense__1445CFF3C4D3A9A4");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex(new[] { "ShopId", "ExpenseDate" }, "IX_Expense_Shop_Date")
                        .IsDescending(false, true);

                    b.ToTable("Expense");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExpenseCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExpenseCategoryId")
                        .HasName("PK__ExpenseC__9C2C63D8C55CE0C5");

                    b.HasIndex(new[] { "Name" }, "UQ_ExpenseCategory_Name")
                        .IsUnique();

                    b.ToTable("ExpenseCategory");
                });

            modelBuilder.Entity("POSsystem.Api.Models.MovementType", b =>
                {
                    b.Property<int>("MovementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MovementTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MovementTypeId")
                        .HasName("PK__Movement__74FB1FF1C1C03246");

                    b.ToTable("MovementType");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A584F36F8E4");

                    b.HasIndex(new[] { "SaleId" }, "IX_Payment_Sale");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NationalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId")
                        .HasName("PK__Person__AA2FFB85553DD75E");

                    b.HasIndex("CountryId");

                    b.HasIndex(new[] { "NationalNumber" }, "UQ_Person_NationalNumber")
                        .IsUnique()
                        .HasFilter("[NationalNumber] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__B40CC6ED9330B356");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<int>("TotalSoldQty")
                        .HasColumnType("int");

                    b.HasKey("VariantId")
                        .HasName("PK__ProductV__0EA233E48AD8091F");

                    b.HasIndex(new[] { "ProductId", "Size", "Color" }, "UQ_ProductVariant_Product_Size_Color")
                        .IsUnique()
                        .HasFilter("[Size] IS NOT NULL AND [Color] IS NOT NULL");

                    b.HasIndex(new[] { "ShopId", "Barcode" }, "UQ_ProductVariant_Shop_Barcode")
                        .IsUnique();

                    b.HasIndex(new[] { "ShopId", "Sku" }, "UX_ProductVariant_Shop_SKU")
                        .IsUnique()
                        .HasFilter("([SKU] IS NOT NULL)");

                    b.ToTable("ProductVariant");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ReturnItem", b =>
                {
                    b.Property<int>("ReturnItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("QuantityReturned")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("SaleItemId")
                        .HasColumnType("int")
                        .HasColumnName("SaleItemID");

                    b.Property<int>("SaleReturnId")
                        .HasColumnType("int")
                        .HasColumnName("SaleReturnID");

                    b.Property<decimal>("TaxRefundAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ReturnItemId")
                        .HasName("PK__ReturnIt__8D87CD1A1DC55DAF");

                    b.HasIndex("SaleItemId");

                    b.HasIndex("SaleReturnId");

                    b.ToTable("ReturnItem");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A673F71C6");

                    b.HasIndex(new[] { "RoleName" }, "UQ_Role_RoleName")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("SaleDiscount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("COMPLETED");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SaleId")
                        .HasName("PK__Sale__1EE3C41F27441767");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ShopId", "SaleDate" }, "IX_Sale_Shop_Date")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "ShopId", "InvoiceNumber" }, "UQ_Sale_Shop_InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleItem", b =>
                {
                    b.Property<int>("SaleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("ProductNameAtSale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<decimal>("TaxAmountAtSale")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("TaxRateAtSale")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TotalCostAtSale")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("TotalPriceAtSale")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("UnitCostAtSale")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("VariantDescriptionAtSale")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.HasKey("SaleItemId")
                        .HasName("PK__SaleItem__C605946103DEFED9");

                    b.HasIndex("ShopId");

                    b.HasIndex("VariantId");

                    b.HasIndex(new[] { "SaleId" }, "IX_SaleItem_Sale");

                    b.ToTable("SaleItem");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleReturn", b =>
                {
                    b.Property<int>("SaleReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleReturnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleReturnId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PARTIAL");

                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<decimal>("TotalRefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("SaleReturnId")
                        .HasName("PK__SaleRetu__2CB01EE26AE553A7");

                    b.HasIndex("SaleId");

                    b.HasIndex("ShopId");

                    b.HasIndex("UserId");

                    b.ToTable("SaleReturn");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SchemaVersion", b =>
                {
                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Version")
                        .HasName("PK__SchemaVe__0F540135AE079F72");

                    b.ToTable("SchemaVersion");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ShopId")
                        .HasName("PK__Shop__67C556291829E8FD");

                    b.HasIndex("CountryId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.StockMovement", b =>
                {
                    b.Property<long>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("StockMovementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockMovementId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserID");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MovementTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MovementTypeID");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("ReferenceID");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<int>("VariantId")
                        .HasColumnType("int")
                        .HasColumnName("VariantID");

                    b.HasKey("StockMovementId")
                        .HasName("PK__StockMov__E963E35C12FD3C2B");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("ShopId");

                    b.HasIndex(new[] { "VariantId", "CreatedAt" }, "IX_StockMovement_Variant_Date")
                        .IsDescending(false, true);

                    b.ToTable("StockMovement");
                });

            modelBuilder.Entity("POSsystem.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC50845295");

                    b.HasIndex("PersonId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShopId");

                    b.HasIndex(new[] { "UserName" }, "UQ_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Category", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("Categories")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Category_Shop");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Expense", b =>
                {
                    b.HasOne("POSsystem.Api.Models.User", "CreatedByUser")
                        .WithMany("Expenses")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Expense_User");

                    b.HasOne("POSsystem.Api.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Expense_Category");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("Expenses")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Expense_Shop");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Payment", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Sale");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Person", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Country", "Country")
                        .WithMany("People")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_Person_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Product", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Shop");

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ProductVariant", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductVariant_Product");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductVariant_Shop");

                    b.Navigation("Product");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ReturnItem", b =>
                {
                    b.HasOne("POSsystem.Api.Models.SaleItem", "SaleItem")
                        .WithMany("ReturnItems")
                        .HasForeignKey("SaleItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnItem_SaleItem");

                    b.HasOne("POSsystem.Api.Models.SaleReturn", "SaleReturn")
                        .WithMany("ReturnItems")
                        .HasForeignKey("SaleReturnId")
                        .IsRequired()
                        .HasConstraintName("FK_ReturnItem_SaleReturn");

                    b.Navigation("SaleItem");

                    b.Navigation("SaleReturn");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Sale", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("Sales")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_Shop");

                    b.HasOne("POSsystem.Api.Models.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Sale_User");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleItem", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleItem_Sale");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("SaleItems")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleItem_Shop");

                    b.HasOne("POSsystem.Api.Models.ProductVariant", "Variant")
                        .WithMany("SaleItems")
                        .HasForeignKey("VariantId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleItem_Variant");

                    b.Navigation("Sale");

                    b.Navigation("Shop");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleReturn", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Sale", "Sale")
                        .WithMany("SaleReturns")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleReturn_Sale");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("SaleReturns")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleReturn_Shop");

                    b.HasOne("POSsystem.Api.Models.User", "User")
                        .WithMany("SaleReturns")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SaleReturn_User");

                    b.Navigation("Sale");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Shop", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Country", "Country")
                        .WithMany("Shops")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_Shop_Country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("POSsystem.Api.Models.StockMovement", b =>
                {
                    b.HasOne("POSsystem.Api.Models.User", "CreatedByUser")
                        .WithMany("StockMovements")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovement_User");

                    b.HasOne("POSsystem.Api.Models.MovementType", "MovementType")
                        .WithMany("StockMovements")
                        .HasForeignKey("MovementTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovement_MovementType");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("StockMovements")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovement_Shop");

                    b.HasOne("POSsystem.Api.Models.ProductVariant", "Variant")
                        .WithMany("StockMovements")
                        .HasForeignKey("VariantId")
                        .IsRequired()
                        .HasConstraintName("FK_StockMovement_Variant");

                    b.Navigation("CreatedByUser");

                    b.Navigation("MovementType");

                    b.Navigation("Shop");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("POSsystem.Api.Models.User", b =>
                {
                    b.HasOne("POSsystem.Api.Models.Person", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Person");

                    b.HasOne("POSsystem.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Role");

                    b.HasOne("POSsystem.Api.Models.Shop", "Shop")
                        .WithMany("Users")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Shop");

                    b.Navigation("Person");

                    b.Navigation("Role");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Country", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("POSsystem.Api.Models.MovementType", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Person", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("POSsystem.Api.Models.ProductVariant", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Sale", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SaleItems");

                    b.Navigation("SaleReturns");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleItem", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("POSsystem.Api.Models.SaleReturn", b =>
                {
                    b.Navigation("ReturnItems");
                });

            modelBuilder.Entity("POSsystem.Api.Models.Shop", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Expenses");

                    b.Navigation("ProductVariants");

                    b.Navigation("Products");

                    b.Navigation("SaleItems");

                    b.Navigation("SaleReturns");

                    b.Navigation("Sales");

                    b.Navigation("StockMovements");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("POSsystem.Api.Models.User", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("SaleReturns");

                    b.Navigation("Sales");

                    b.Navigation("StockMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
